# Generated by Django 5.0.6 on 2024-05-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ManyToManyField(to='quotes.author'),
        ),
    ]
